# General
#region parameters.

study_region_name: [Odense, Ringsted]
scenario: [ref]
technologies: [solar]

#snakemake specific parameters
cores: 4
snakefile: snakemake/Snakefile
weather_years: [2019]

stages:
  spatial_data_prep: true
  exclusion: true
  suitability: false
  timeseries: true
  weather_data_prep: false
  weather_bias_adjust: false
  energy_profiles: false